; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:dfrobot_firebeetle2_esp32s3]
platform = espressif32
board = dfrobot_firebeetle2_esp32s3
framework = arduino

lib_deps =
	bblanchon/ArduinoJson
	adafruit/Adafruit GFX Library
	adafruit/Adafruit ST7735 and ST7789 Library
	lvgl/lvgl@^8.3.0


build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D LV_CONF_INCLUDE_SIMPLE
	-I include

; 串口监视器配置
monitor_speed = 115200

; 防止打开串口监视器时 DTR/RTS 触发自动复位（避免看到 rst:0x15 USB_UART_CHIP_RESET）
monitor_dtr = 0
monitor_rts = 0